name: Github Action for Jenkinsdev
run-name : ${{github.actor}} is running the Github Action
on: [push]
jobs :
    First-Job:
        runs-on: ubuntu-latest
        steps:
            - run : echo "Job running"
              name : "Demo Script"
    Salesforce-Job:
        runs-on : ubuntu-latest
        steps :
            - name : "Checkout to the rep"
              uses: actions/checkout@v4.2.1
              with:
                fetch-depth: 0
            # - name : "npm init"
            #   run : npm init
            - name : "ES Lint version"
              run : npm info eslint
            - name : "Install npm module"
              run : npm update --force
            - name : "ES Lint version"
              run : npm info eslint
            - name: "Install sfdx cli"
              run : npm install @salesforce/cli --global
            - name : "Print versions"
              run : sf --version
            - name : "Print  npm version"
              run : npm --version



               


    